export const EPISODE_DETAILS_REQUEST = 'EPISODE/EPISODE_DETAILS_REQUEST';
export const EPISODE_DETAILS_SUCCESS = 'EPISODE/EPISODE_DETAILS_SUCCESS';
export const EPISODE_DETAILS_FAILURE = 'EPISODE/EPISODE_DETAILS_FAILURE';