export const SHOW_DETAILS_REQUEST = 'SHOW/SHOW_DETAILS_REQUEST';
export const SHOW_DETAILS_SUCCESS = 'SHOW/SHOW_DETAILS_SUCCESS';
export const SHOW_DETAILS_FAILURE = 'SHOW/SHOW_DETAILS_FAILURE';

export const SHOW_EPISODE_LIST_REQUEST = 'SHOW/SHOW_EPISODE_LIST_REQUEST';
export const SHOW_EPISODE_LIST_SUCCESS = 'SHOW/SHOW_EPISODE_LIST_SUCCESS';
export const SHOW_EPISODE_LIST_FAILURE = 'SHOW/SHOW_EPISODE_LIST_FAILURE';